# coding: utf-8

"""
    ThirdPartyApi

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.metadata_api import MetadataApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMetadataApi(unittest.TestCase):
    """MetadataApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.metadata_api.MetadataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_metadata_get(self):
        """Test case for metadata_get

        Gets metadata of all PV systems for the user, identified by the access token.  # noqa: E501
        """
        pass

    def test_metadata_get_0(self):
        """Test case for metadata_get_0

        Gets metadata of the PV systems with the given ID.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
