# coding: utf-8

"""
    ThirdPartyApi

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.energy_flow_values_api import EnergyFlowValuesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEnergyFlowValuesApi(unittest.TestCase):
    """EnergyFlowValuesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.energy_flow_values_api.EnergyFlowValuesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_energy_flow_values_get_for_pv_system(self):
        """Test case for energy_flow_values_get_for_pv_system

        Gets energy flow values for given pv system (only available with expert package).  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
