# coding: utf-8

"""
    ThirdPartyApi

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.aggregated_values_api import AggregatedValuesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAggregatedValuesApi(unittest.TestCase):
    """AggregatedValuesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.aggregated_values_api.AggregatedValuesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_aggregated_values_get_month_values(self):
        """Test case for aggregated_values_get_month_values

        Gets dayly aggregated values for given pv system, year and month  (only available with expert package).  # noqa: E501
        """
        pass

    def test_aggregated_values_get_total_values(self):
        """Test case for aggregated_values_get_total_values

        Gets yearly aggregated values for given pv system (only available with expert package).  # noqa: E501
        """
        pass

    def test_aggregated_values_get_year_values(self):
        """Test case for aggregated_values_get_year_values

        Gets monthly aggregated values for given pv system and year  (only available with expert package).  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
