# coding: utf-8

"""
    ThirdPartyApi

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.realtime_inverter_expert_model import RealtimeInverterExpertModel  # noqa: E501
from swagger_client.rest import ApiException


class TestRealtimeInverterExpertModel(unittest.TestCase):
    """RealtimeInverterExpertModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRealtimeInverterExpertModel(self):
        """Test RealtimeInverterExpertModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.realtime_inverter_expert_model.RealtimeInverterExpertModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
