# coding: utf-8

"""
    ThirdPartyApi

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.authentication_api import AuthenticationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.authentication_api.AuthenticationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_authentication_login(self):
        """Test case for authentication_login

        User login to get AccessToken to query API data.  # noqa: E501
        """
        pass

    def test_authentication_refresh(self):
        """Test case for authentication_refresh

        Refresh AccessToken, i.e. get a new AccessToken without loging in.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
