# coding: utf-8

"""
    ThirdPartyApi

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.pv_system_metadata_expert_model import PvSystemMetadataExpertModel  # noqa: E501
from swagger_client.rest import ApiException


class TestPvSystemMetadataExpertModel(unittest.TestCase):
    """PvSystemMetadataExpertModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPvSystemMetadataExpertModel(self):
        """Test PvSystemMetadataExpertModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.pv_system_metadata_expert_model.PvSystemMetadataExpertModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
